name: expense_tracker
description: A new Flutter project.

publish_to: 'none' # Remains for private publishing control

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.0.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  uuid: ^4.5.1
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  random_string: ^2.3.1
  permission_handler: ^12.0.0+1
  share_plus: ^11.0.0
  pdf: ^3.11.3
  path_provider: ^2.1.2 
  google_sign_in: ^6.3.0
  printing: ^5.14.2
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo1.png
    - assets/images/logo2.png
    - assets/images/usericon.png
    - assets/images/user.jpg
    - assets/Roboto-Regular.ttf
  # Custom fonts can be added here if needed in the future
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
